# Generated by Django 6.0.2 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_chatthread_chatmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credits",
            field=models.PositiveIntegerField(default=20),
        ),
    ]
