# Generated by Django 6.0.2 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="code",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="website",
            name="deploy_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="website",
            name="deployed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
